package aura.orchestrator.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/** Room entities. IDs are strings generated by the core [aura.core.Ids] helper so
 *  they survive serialization across the AURA protocol. */

@Entity(tableName = "conversations")
data class ConversationEntity(
    @PrimaryKey val id: String,
    val title: String,
    val projectId: String? = null,
    val createdAtEpochMs: Long = System.currentTimeMillis()
)

@Entity(tableName = "messages")
data class MessageEntity(
    @PrimaryKey val id: String,
    val conversationId: String,
    val role: String,
    val content: String,
    val createdAtEpochMs: Long = System.currentTimeMillis()
)

@Entity(tableName = "projects")
data class ProjectEntity(
    @PrimaryKey val id: String,
    val name: String,
    val description: String = "",
    val createdAtEpochMs: Long = System.currentTimeMillis()
)

@Entity(tableName = "tasks")
data class TaskEntity(
    @PrimaryKey val id: String,
    val title: String,
    val complexity: String,
    val status: String,
    val projectId: String? = null,
    val detail: String = "",
    val source: String = "",
    val progress: Int = 0,
    val createdAtEpochMs: Long = System.currentTimeMillis(),
    val updatedAtEpochMs: Long = System.currentTimeMillis()
)

@Entity(tableName = "execution_logs")
data class ExecutionLogEntity(
    @PrimaryKey val id: String,
    val taskId: String? = null,
    val agentId: String? = null,
    val pluginId: String? = null,
    val level: String = "info",
    val message: String = "",
    val createdAtEpochMs: Long = System.currentTimeMillis()
)

@Entity(tableName = "memories")
data class MemoryEntity(
    @PrimaryKey val id: String,
    val text: String,
    val importance: Double = 0.5,
    val layer: String = "project",
    val source: String = "user",
    val projectId: String? = null,
    val createdAtEpochMs: Long = System.currentTimeMillis()
)
